### ISSUE TITLE
Improper formating

### ISSUE THREAD

**Issue by BenHyatt** [KoalaMuffin/Administrative-Suite#3]
Inside the James Corp Suite application, the Kick program isn't properly indented.  I submitted a pull request but it would be much easier if I was a contributor.

**Comment by KoalaMuffin** [comment]
Hi Ben,
Thank you for the feedback. We've been aware of the problem and it'll be fixed in the final version of the suite. We're glad you're interested in our products. We strive to make the customer experience the best it can be.
- JamesCorp
